version: "3.9"

services:
  vault:
    container_name: vault
    image: vault:1.13.0
    ports:
      - "8200:8200"
    environment:
      - VAULT_DEV_ROOT_TOKEN_ID=root
  keycloak:
    container_name: keycloak
    image: bitnami/keycloak:21.0.2-debian-11-r2
    ports:
      - "10000:8080"
    environment:
      - "KEYCLOAK_ADMIN_USER=admin"
      - "KEYCLOAK_ADMIN_PASSWORD=admin"
      - "KEYCLOAK_MANAGEMENT_USER=admin"
      - "KEYCLOAK_MANAGEMENT_PASSWORD=admin"
      - "KEYCLOAK_DATABASE_VENDOR=dev-file"
  kafka:
    image: bitnami/kafka:3.4.0
    container_name: kafka
    ports:
      - "9092:9092"
  kibana:
    image: bitnami/kibana:7.17.9
    container_name: kibana
    ports:
      - "5601:5601"
    environment:
      - KIBANA_ELiSTICSEARCH_URL=elasticsearch
    volumes:
      - "${PWD}/data:/bitnami/kibana"
  elasticsearch:
    image: bitnami/elasticsearch:7.17.10
    container_name: elasticsearch
    volumes:
      - "${PWD}/data:/bitnami/elasticsearch/data"
      #      - "${PWD}/conf/elasticsearch.yaml:/opt/bitnami/elasticsearch/config/elasticsearch.yml"
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ELASTICSEARCH_HEAP_SIZE: 1024m
  logstash:
    image: bitnami/logstash:7.17.10
    container_name: logstash
    ports:
      - "5000:8080"
    volumes:
      - "${PWD}/data:/bitnami"
      - "${PWD}/conf:/bitnami/logstash/pipeline"
    environment:
      LOGSTASH_PIPELINE_CONF_FILENAME: logstash.conf
  zipkin:
    image: openzipkin/zipkin:2.24
    container_name: zipkin
    ports:
      - "9411:9411"
    environment:
      - "STORAGE_TYPE=elasticsearch"
      - "ES_HOSTS=elasticsearch:9200"