server:
  port: 9001
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: {cipher}2e6edbcaf0f7677f1098cbbb2974e09bc7d38cbd504321cf0ad7e5e359edf04d
    hikari:
      connection-timeout: 2000
      maximum-pool-size: 5
management:
  endpoints:
    web:
      exposure:
        include: "*"
    enabled-by-default: true

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8070/eureka